# Generated by Django 5.2.5 on 2026-07-11 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('principal_id', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=160)),
                ('resource', models.CharField(blank=True, max_length=255)),
                ('decision', models.CharField(max_length=16)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Policy decision',
                'verbose_name_plural': 'Policy decisions',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_id', models.CharField(max_length=128, unique=True)),
                ('role', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Principal',
                'verbose_name_plural': 'Principals',
            },
        ),
        migrations.CreateModel(
            name='RestrictedSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64, unique=True)),
                ('reason', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Restricted symbol',
                'verbose_name_plural': 'Restricted symbols',
            },
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=160)),
                ('resource_pattern', models.CharField(default='*', max_length=255)),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='allow', max_length=16)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='policy.principal')),
            ],
            options={
                'verbose_name': 'Capability',
                'verbose_name_plural': 'Capabilities',
                'unique_together': {('principal', 'action', 'resource_pattern')},
            },
        ),
    ]
