# Generated by Django 5.2.5 on 2026-06-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='McpToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool_name', models.CharField(max_length=160)),
                ('principal_id', models.CharField(default='unknown', max_length=128)),
                ('status', models.CharField(default='recorded', max_length=32)),
                ('request', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('result_hash', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'MCP tool call',
                'verbose_name_plural': 'MCP tool calls',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='McpToolDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='general', max_length=64)),
                ('capability_required', models.CharField(blank=True, max_length=160)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('risk_level', models.CharField(default='read', max_length=32)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('requires_approval', models.BooleanField(default=False)),
                ('audit_required', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MCP tool definition',
                'verbose_name_plural': 'MCP tool definitions',
            },
        ),
    ]
