# Generated by Django 5.2.5 on 2026-06-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcptooldefinition',
            name='experimental',
            field=models.BooleanField(default=False),
        ),
    ]
