# Generated by Django 5.2.5 on 2026-06-12 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0002_mcptooldefinition_experimental'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('transport', models.CharField(default='stdio', max_length=32)),
                ('command', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('args', models.JSONField(blank=True, default=list)),
                ('env', models.JSONField(blank=True, default=dict)),
                ('credential_ref', models.CharField(blank=True, max_length=255)),
                ('trust_level', models.CharField(default='unreviewed', max_length=32)),
                ('enabled', models.BooleanField(default=False)),
                ('last_status', models.CharField(default='not_checked', max_length=32)),
                ('last_error', models.TextField(blank=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MCP connector',
                'verbose_name_plural': 'MCP connectors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='McpExternalTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primitive', models.CharField(default='tool', max_length=32)),
                ('external_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('schema_hash', models.CharField(blank=True, max_length=64)),
                ('category', models.CharField(default='unknown', max_length=64)),
                ('risk_level', models.CharField(default='unknown', max_length=32)),
                ('sensitivity', models.CharField(default='unknown', max_length=32)),
                ('canonical_capability', models.CharField(blank=True, max_length=160)),
                ('proxy_mode', models.CharField(default='blocked', max_length=32)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=False)),
                ('review_status', models.CharField(default='review_required', max_length=32)),
                ('drift_detected', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_tools', to='mcp.mcpconnector')),
            ],
            options={
                'verbose_name': 'external MCP tool',
                'verbose_name_plural': 'external MCP tools',
                'ordering': ['connector__name', 'primitive', 'external_name'],
            },
        ),
        migrations.CreateModel(
            name='McpExternalToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connector_name', models.CharField(max_length=160)),
                ('external_name', models.CharField(max_length=200)),
                ('principal_id', models.CharField(default='unknown', max_length=128)),
                ('proxy_mode', models.CharField(default='blocked', max_length=32)),
                ('decision', models.CharField(default='denied', max_length=32)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('request', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('result_hash', models.CharField(blank=True, max_length=64)),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
                ('external_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='mcp.mcpexternaltool')),
            ],
            options={
                'verbose_name': 'external MCP tool call',
                'verbose_name_plural': 'external MCP tool calls',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='McpExternalToolPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_or_role', models.CharField(max_length=128)),
                ('capability', models.CharField(blank=True, max_length=160)),
                ('decision', models.CharField(default='allow', max_length=16)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='mcp.mcpexternaltool')),
            ],
            options={
                'verbose_name': 'external MCP permission',
                'verbose_name_plural': 'external MCP permissions',
                'ordering': ['external_tool__external_name', 'principal_or_role'],
            },
        ),
        migrations.AddConstraint(
            model_name='mcpexternaltool',
            constraint=models.UniqueConstraint(fields=('connector', 'primitive', 'external_name'), name='unique_external_mcp_primitive'),
        ),
        migrations.AddConstraint(
            model_name='mcpexternaltoolpermission',
            constraint=models.UniqueConstraint(fields=('external_tool', 'principal_or_role', 'capability'), name='unique_external_mcp_permission'),
        ),
    ]
