# Generated by Django 5.2.5 on 2026-06-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(max_length=160, unique=True)),
                ('order_intent_id', models.CharField(max_length=160)),
                ('approved_by', models.CharField(max_length=128)),
                ('valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Approval receipt',
                'verbose_name_plural': 'Approval receipts',
            },
        ),
        migrations.CreateModel(
            name='ExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_intent_id', models.CharField(max_length=160)),
                ('approval_receipt_id', models.CharField(blank=True, max_length=160)),
                ('idempotency_key', models.CharField(blank=True, max_length=220, null=True, unique=True)),
                ('adapter', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_id', models.CharField(default='default-paper', max_length=120)),
                ('account_id', models.CharField(default='local-paper', max_length=120)),
                ('strategy_id', models.CharField(default='default-strategy', max_length=120)),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Execution result',
                'verbose_name_plural': 'Execution results',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_id', models.CharField(max_length=160, unique=True)),
                ('symbol', models.CharField(max_length=64)),
                ('side', models.CharField(max_length=8)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('limit_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('currency', models.CharField(default='KRW', max_length=16)),
                ('broker', models.CharField(max_length=64)),
                ('estimated_notional_krw', models.DecimalField(decimal_places=2, max_digits=24)),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField()),
                ('portfolio_id', models.CharField(default='default-paper', max_length=120)),
                ('account_id', models.CharField(default='local-paper', max_length=120)),
                ('strategy_id', models.CharField(default='default-strategy', max_length=120)),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Order intent',
                'verbose_name_plural': 'Order intents',
            },
        ),
    ]
