# Generated by Django 5.2.5 on 2026-06-14 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_brokerconnection_brokeraccount_instrumentmap'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalreceipt',
            name='approved_order_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='approvalreceipt',
            name='approved_time_in_force',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='approvalreceipt',
            name='broker_account_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='approvalreceipt',
            name='broker_connection_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='approvalreceipt',
            name='exact_intent_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='approvalreceipt',
            name='max_notional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='approvalreceipt',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='approvalreceipt',
            name='max_slippage_bps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalreceipt',
            name='order_ticket_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='approvalreceipt',
            name='quote_as_of_requirement',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='approvalreceipt',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=160, unique=True)),
                ('source', models.CharField(default='web', max_length=32)),
                ('portfolio_id', models.CharField(default='default-paper', max_length=120)),
                ('account_id', models.CharField(default='local-paper', max_length=120)),
                ('strategy_id', models.CharField(default='default-strategy', max_length=120)),
                ('instrument_id', models.CharField(blank=True, max_length=120)),
                ('symbol', models.CharField(max_length=64)),
                ('side', models.CharField(max_length=8)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('order_type', models.CharField(default='limit', max_length=32)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('time_in_force', models.CharField(default='day', max_length=32)),
                ('estimated_notional', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('currency', models.CharField(default='KRW', max_length=16)),
                ('status', models.CharField(default='DRAFT', max_length=32)),
                ('current_state', models.CharField(default='DRAFT', max_length=32)),
                ('intent_hash', models.CharField(blank=True, max_length=64)),
                ('user_visible_summary', models.TextField(blank=True)),
                ('created_by', models.CharField(default='portfolio-manager', max_length=128)),
                ('natural_language_source', models.TextField(blank=True)),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_tickets', to='integrations.brokeraccount')),
                ('broker_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_tickets', to='integrations.brokerconnection')),
            ],
            options={
                'verbose_name': 'Order ticket',
                'verbose_name_plural': 'Order tickets',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('actor', models.CharField(default='system', max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.orderticket')),
            ],
            options={
                'verbose_name': 'Order event',
                'verbose_name_plural': 'Order events',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderCheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(max_length=32)),
                ('decision', models.CharField(max_length=16)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('quote_as_of', models.CharField(blank=True, max_length=80)),
                ('source_snapshot_ref', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_runs', to='orders.orderticket')),
            ],
            options={
                'verbose_name': 'Order check run',
                'verbose_name_plural': 'Order check runs',
                'ordering': ['check_type', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_order_id', models.CharField(max_length=160)),
                ('fill_id', models.CharField(max_length=160)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('currency', models.CharField(default='KRW', max_length=16)),
                ('filled_at', models.DateTimeField()),
                ('raw_payload_hash', models.CharField(blank=True, max_length=64)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='orders.orderticket')),
            ],
            options={
                'verbose_name': 'Fill',
                'verbose_name_plural': 'Fills',
                'ordering': ['-filled_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('ticket', 'broker_order_id', 'fill_id'), name='unique_fill_per_ticket')],
            },
        ),
        migrations.CreateModel(
            name='BrokerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_order_id', models.CharField(max_length=160)),
                ('broker_status', models.CharField(max_length=64)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('raw_status_payload_hash', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_orders', to='orders.orderticket')),
            ],
            options={
                'verbose_name': 'Broker order',
                'verbose_name_plural': 'Broker orders',
                'ordering': ['-submitted_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('ticket', 'broker_order_id'), name='unique_broker_order_per_ticket')],
            },
        ),
    ]
