# Generated by TradingCodex on 2026-06-14

from __future__ import annotations

import hashlib
import json
from decimal import Decimal
from typing import Any

from django.db import migrations


def _stable_hash(payload: Any) -> str:
    return hashlib.sha256(json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8")).hexdigest()


def _decimal_or_none(value: Any) -> Decimal | None:
    if value in (None, ""):
        return None
    try:
        return Decimal(str(value))
    except Exception:
        return None


def _legacy_payload(intent: Any) -> dict[str, Any]:
    payload = intent.payload or {}
    if isinstance(payload, dict) and isinstance(payload.get("order_intent"), dict):
        order = dict(payload["order_intent"])
    else:
        order = {}
    order.setdefault("id", intent.intent_id)
    order.setdefault("order_ticket_id", order.get("id") or intent.intent_id)
    order.setdefault("symbol", intent.symbol)
    order.setdefault("side", intent.side)
    order.setdefault("quantity", str(intent.quantity))
    order.setdefault("limit_price", str(intent.limit_price))
    order.setdefault("currency", intent.currency)
    order.setdefault("broker", intent.broker)
    order.setdefault("broker_connection_id", order.get("broker") or intent.broker)
    order.setdefault("estimated_notional_krw", str(intent.estimated_notional_krw))
    order.setdefault("created_by", intent.created_by)
    order.setdefault("created_at", intent.created_at.isoformat())
    order.setdefault("portfolio_id", intent.portfolio_id)
    order.setdefault("account_id", intent.account_id)
    order.setdefault("strategy_id", intent.strategy_id)
    order.setdefault("order_type", "limit")
    order.setdefault("time_in_force", "day")
    return order


def migrate_order_intents(apps: Any, schema_editor: Any) -> None:
    OrderIntent = apps.get_model("orders", "OrderIntent")
    OrderTicket = apps.get_model("orders", "OrderTicket")
    BrokerConnection = apps.get_model("integrations", "BrokerConnection")
    BrokerAccount = apps.get_model("integrations", "BrokerAccount")

    for intent in OrderIntent.objects.all().iterator():
        order = _legacy_payload(intent)
        ticket_id = str(order.get("order_ticket_id") or order.get("id") or intent.intent_id)
        if not ticket_id or OrderTicket.objects.filter(ticket_id=ticket_id).exists():
            continue

        broker_id = str(order.get("broker_connection_id") or order.get("broker") or "")
        broker_connection = BrokerConnection.objects.filter(broker_id=broker_id).first() if broker_id else None
        broker_account_id = str(order.get("broker_account_id") or order.get("account_id") or "")
        broker_account = None
        if broker_connection is not None and broker_account_id:
            broker_account = BrokerAccount.objects.filter(
                broker_connection=broker_connection,
                broker_account_id=broker_account_id,
            ).first()

        quantity = _decimal_or_none(order.get("quantity")) or Decimal("0")
        limit_price = _decimal_or_none(order.get("limit_price"))
        estimated_notional = _decimal_or_none(order.get("estimated_notional_krw") or order.get("estimated_notional"))
        source_payload = {
            "canonical_order": order,
            "migrated_from": {"model": "orders.OrderIntent", "intent_id": intent.intent_id},
            "legacy_payload": intent.payload or {},
        }
        OrderTicket.objects.create(
            ticket_id=ticket_id,
            source="migration",
            portfolio_id=str(order.get("portfolio_id") or intent.portfolio_id),
            account_id=str(order.get("account_id") or intent.account_id),
            strategy_id=str(order.get("strategy_id") or intent.strategy_id),
            broker_connection=broker_connection,
            broker_account=broker_account,
            instrument_id=str(order.get("instrument_id") or order.get("symbol") or intent.symbol),
            symbol=str(order.get("symbol") or intent.symbol).upper(),
            side=str(order.get("side") or intent.side).lower(),
            quantity=quantity,
            order_type=str(order.get("order_type") or "limit"),
            limit_price=limit_price,
            stop_price=_decimal_or_none(order.get("stop_price")),
            time_in_force=str(order.get("time_in_force") or "day"),
            estimated_notional=estimated_notional,
            currency=str(order.get("currency") or intent.currency),
            status="DRAFT",
            current_state="DRAFT",
            intent_hash=_stable_hash(order),
            user_visible_summary=f"{str(order.get('side') or intent.side).upper()} {quantity} {str(order.get('symbol') or intent.symbol).upper()}",
            created_by=str(order.get("created_by") or intent.created_by),
            natural_language_source="",
            workspace_context=intent.workspace_context or {},
            payload=source_payload,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_approvalreceipt_approved_order_type_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_order_intents, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="OrderIntent",
        ),
    ]
