# Generated by TradingCodex on 2026-06-14

from __future__ import annotations

from typing import Any

from django.db import migrations, models


def copy_order_intent_fields(apps: Any, schema_editor: Any) -> None:
    ApprovalReceipt = apps.get_model("orders", "ApprovalReceipt")
    for receipt in ApprovalReceipt.objects.all().iterator():
        updates: list[str] = []
        if not receipt.order_ticket_id and receipt.order_intent_id:
            receipt.order_ticket_id = receipt.order_intent_id
            updates.append("order_ticket_id")
        if not receipt.exact_order_hash and receipt.exact_intent_hash:
            receipt.exact_order_hash = receipt.exact_intent_hash
            updates.append("exact_order_hash")
        if updates:
            receipt.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_migrate_orderintent_to_orderticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalreceipt",
            name="exact_order_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(copy_order_intent_fields, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="approvalreceipt",
            name="order_intent_id",
        ),
        migrations.RemoveField(
            model_name="approvalreceipt",
            name="exact_intent_hash",
        ),
        migrations.AlterField(
            model_name="approvalreceipt",
            name="order_ticket_id",
            field=models.CharField(max_length=160),
        ),
        migrations.RenameField(
            model_name="executionresult",
            old_name="order_intent_id",
            new_name="order_ticket_id",
        ),
        migrations.RenameField(
            model_name="orderticket",
            old_name="intent_hash",
            new_name="payload_hash",
        ),
    ]
