# Generated by Django 5.2 on 2026-07-10

import django.db.models.deletion
from django.db import migrations, models


def bind_existing_receipts(apps, schema_editor) -> None:
    ApprovalReceipt = apps.get_model("orders", "ApprovalReceipt")
    OrderTicket = apps.get_model("orders", "OrderTicket")
    tickets = {ticket.ticket_id: ticket.pk for ticket in OrderTicket.objects.all().only("pk", "ticket_id")}
    for receipt in ApprovalReceipt.objects.filter(ticket__isnull=True).only("pk", "order_ticket_id"):
        ticket_pk = tickets.get(receipt.order_ticket_id)
        if ticket_pk:
            ApprovalReceipt.objects.filter(pk=receipt.pk).update(ticket_id=ticket_pk)


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_order_intent_compat_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalreceipt",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_receipts",
                to="orders.orderticket",
            ),
        ),
        migrations.AddField(
            model_name="approvalreceipt",
            name="consumed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="approvalreceipt",
            name="superseded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="executionresult",
            name="provider_invoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="executionresult",
            name="finalized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(bind_existing_receipts, migrations.RunPython.noop),
    ]
