# Generated by Django 5.2.5 on 2026-06-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversePlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universe_id', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('enabled', models.BooleanField(default=True)),
                ('research_only_default', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Universe plugin',
                'verbose_name_plural': 'Universe plugins',
            },
        ),
    ]
