# Generated by Django 5.2.5 on 2026-07-11 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdapterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adapter_id', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(default='execution', max_length=64)),
                ('enabled', models.BooleanField(default=False)),
                ('live', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Adapter definition',
                'verbose_name_plural': 'Adapter definitions',
            },
        ),
        migrations.CreateModel(
            name='BrokerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_id', models.CharField(max_length=120, unique=True)),
                ('provider_id', models.CharField(db_index=True, max_length=120)),
                ('display_name', models.CharField(max_length=160)),
                ('transport', models.CharField(max_length=32)),
                ('status', models.CharField(default='read_only', max_length=32)),
                ('credential_ref', models.CharField(blank=True, max_length=255)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('enabled_read_scopes', models.JSONField(blank=True, default=list)),
                ('enabled_trade_scopes', models.JSONField(blank=True, default=list)),
                ('trust_level', models.CharField(default='unreviewed', max_length=32)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_status', models.CharField(default='not_checked', max_length=32)),
                ('drift_status', models.CharField(default='none', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker connection',
                'verbose_name_plural': 'Broker connections',
                'ordering': ['display_name', 'broker_id'],
            },
        ),
        migrations.CreateModel(
            name='BrokerProviderSourceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.CharField(max_length=180)),
                ('workspace_path_hash', models.CharField(max_length=64)),
                ('provider_id', models.CharField(max_length=120)),
                ('relative_path', models.CharField(max_length=255)),
                ('source_sha256', models.CharField(max_length=64)),
                ('bundle_sha256', models.CharField(max_length=64)),
                ('snapshot_relative_path', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('revoked', 'Revoked')], default='approved', max_length=16)),
                ('approved_by', models.CharField(default='local-operator', max_length=120)),
                ('approved_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Broker provider source approval',
                'verbose_name_plural': 'Broker provider source approvals',
                'ordering': ['-approved_at', '-id'],
                'indexes': [models.Index(fields=['workspace_id', 'workspace_path_hash', 'provider_id', 'status'], name='integration_ws_provider_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('workspace_id', 'workspace_path_hash', 'provider_id'), name='uniq_active_ws_provider'), models.UniqueConstraint(fields=('workspace_id', 'workspace_path_hash', 'provider_id', 'relative_path', 'source_sha256', 'bundle_sha256'), name='uniq_ws_provider_source')],
            },
        ),
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_account_id', models.CharField(max_length=160)),
                ('account_label', models.CharField(blank=True, max_length=160)),
                ('account_type', models.CharField(max_length=64)),
                ('base_currency', models.CharField(max_length=16)),
                ('masked_identifier', models.CharField(blank=True, max_length=120)),
                ('trading_enabled', models.BooleanField(default=False)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('broker_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='integrations.brokerconnection')),
            ],
            options={
                'verbose_name': 'Broker account',
                'verbose_name_plural': 'Broker accounts',
                'ordering': ['broker_connection__display_name', 'broker_account_id'],
                'constraints': [models.UniqueConstraint(fields=('broker_connection', 'broker_account_id'), name='unique_broker_account_per_connection')],
            },
        ),
        migrations.CreateModel(
            name='InstrumentMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_symbol', models.CharField(max_length=64)),
                ('broker_symbol', models.CharField(max_length=120)),
                ('exchange', models.CharField(blank=True, max_length=64)),
                ('asset_type', models.CharField(default='equity', max_length=64)),
                ('currency', models.CharField(default='USD', max_length=16)),
                ('tick_size', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('min_order_quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('broker_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_maps', to='integrations.brokerconnection')),
            ],
            options={
                'verbose_name': 'Instrument map',
                'verbose_name_plural': 'Instrument maps',
                'ordering': ['canonical_symbol', 'broker_symbol'],
                'constraints': [models.UniqueConstraint(fields=('broker_connection', 'canonical_symbol', 'broker_symbol'), name='unique_instrument_map_per_broker')],
            },
        ),
    ]
