# Generated by Django 5.2.5 on 2026-06-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdapterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adapter_id', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(default='execution', max_length=64)),
                ('enabled', models.BooleanField(default=False)),
                ('live', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Adapter definition',
                'verbose_name_plural': 'Adapter definitions',
            },
        ),
    ]
