# Generated by Django 5.2.5 on 2026-06-14 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_id', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('transport', models.CharField(default='paper', max_length=32)),
                ('adapter_type', models.CharField(default='paper', max_length=64)),
                ('status', models.CharField(default='read_only', max_length=32)),
                ('credential_ref', models.CharField(blank=True, max_length=255)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('enabled_read_scopes', models.JSONField(blank=True, default=list)),
                ('enabled_trade_scopes', models.JSONField(blank=True, default=list)),
                ('trust_level', models.CharField(default='unreviewed', max_length=32)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_status', models.CharField(default='not_checked', max_length=32)),
                ('drift_status', models.CharField(default='none', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker connection',
                'verbose_name_plural': 'Broker connections',
                'ordering': ['display_name', 'broker_id'],
            },
        ),
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_account_id', models.CharField(max_length=160)),
                ('account_label', models.CharField(blank=True, max_length=160)),
                ('account_type', models.CharField(default='paper', max_length=64)),
                ('base_currency', models.CharField(default='KRW', max_length=16)),
                ('masked_identifier', models.CharField(blank=True, max_length=120)),
                ('trading_enabled', models.BooleanField(default=False)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('broker_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='integrations.brokerconnection')),
            ],
            options={
                'verbose_name': 'Broker account',
                'verbose_name_plural': 'Broker accounts',
                'ordering': ['broker_connection__display_name', 'broker_account_id'],
                'constraints': [models.UniqueConstraint(fields=('broker_connection', 'broker_account_id'), name='unique_broker_account_per_connection')],
            },
        ),
        migrations.CreateModel(
            name='InstrumentMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_symbol', models.CharField(max_length=64)),
                ('broker_symbol', models.CharField(max_length=120)),
                ('exchange', models.CharField(blank=True, max_length=64)),
                ('asset_type', models.CharField(default='equity', max_length=64)),
                ('currency', models.CharField(default='KRW', max_length=16)),
                ('tick_size', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('min_order_quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('broker_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_maps', to='integrations.brokerconnection')),
            ],
            options={
                'verbose_name': 'Instrument map',
                'verbose_name_plural': 'Instrument maps',
                'ordering': ['canonical_symbol', 'broker_symbol'],
                'constraints': [models.UniqueConstraint(fields=('broker_connection', 'canonical_symbol', 'broker_symbol'), name='unique_instrument_map_per_broker')],
            },
        ),
    ]
