# Generated by Django 5.2.5 on 2026-06-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_principal', models.CharField(default='system', max_length=128)),
                ('source', models.CharField(default='service', max_length=32)),
                ('action', models.CharField(max_length=160)),
                ('resource', models.CharField(blank=True, max_length=255)),
                ('decision', models.CharField(default='recorded', max_length=32)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('result_hash', models.CharField(blank=True, max_length=64)),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Audit event',
                'verbose_name_plural': 'Audit events',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
