# Generated by Django 5.2.5 on 2026-06-12 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=180, unique=True)),
                ('lane', models.CharField(max_length=80)),
                ('universe', models.CharField(default='public_equity', max_length=80)),
                ('readiness_label', models.CharField(default='factual-baseline', max_length=80)),
                ('status', models.CharField(default='open', max_length=32)),
                ('original_request', models.TextField(blank=True)),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workflow run',
                'verbose_name_plural': 'Workflow runs',
            },
        ),
        migrations.CreateModel(
            name='ArtifactRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('artifact_type', models.CharField(max_length=80)),
                ('role', models.CharField(blank=True, max_length=128)),
                ('handoff_state', models.CharField(choices=[('accepted', 'accepted'), ('revise', 'revise'), ('blocked', 'blocked'), ('waiting', 'waiting')], default='waiting', max_length=32)),
                ('hero', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='workflows.workflowrun')),
            ],
            options={
                'verbose_name': 'Artifact reference',
                'verbose_name_plural': 'Artifact references',
            },
        ),
    ]
