# Generated by Django 5.2.5 on 2026-06-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.CharField(max_length=80, unique=True)),
                ('path_hash', models.CharField(max_length=64, unique=True)),
                ('project_name', models.CharField(max_length=180)),
                ('path', models.CharField(max_length=1024)),
                ('git_remote', models.CharField(blank=True, max_length=512)),
                ('git_branch', models.CharField(blank=True, max_length=180)),
                ('active_profile', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workspace context',
                'verbose_name_plural': 'Workspace contexts',
                'ordering': ['project_name', 'id'],
            },
        ),
    ]
