# Generated by Django 5.2.5 on 2026-06-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.CharField(max_length=220, unique=True)),
                ('type', models.CharField(max_length=32)),
                ('target', models.CharField(max_length=128)),
                ('skill', models.CharField(max_length=160)),
                ('status', models.CharField(default='proposed', max_length=32)),
                ('approved_by', models.CharField(blank=True, max_length=128)),
                ('execution_sensitive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Skill proposal',
                'verbose_name_plural': 'Skill proposals',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_hash', models.CharField(max_length=64, unique=True)),
                ('project_name', models.CharField(max_length=180)),
                ('path', models.CharField(max_length=1024)),
                ('git_remote', models.CharField(blank=True, max_length=512)),
                ('git_branch', models.CharField(blank=True, max_length=180)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workspace context',
                'verbose_name_plural': 'Workspace contexts',
                'ordering': ['project_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoleSkillAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=128)),
                ('skill', models.CharField(max_length=160)),
                ('enabled', models.BooleanField(default=True)),
                ('source', models.CharField(default='bootstrap', max_length=64)),
            ],
            options={
                'verbose_name': 'Role skill assignment',
                'verbose_name_plural': 'Role skill assignments',
                'unique_together': {('role', 'skill')},
            },
        ),
    ]
