# Generated by TradingCodex on 2026-06-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("harness", "0002_workspace_identity_profile"),
    ]

    operations = [
        migrations.DeleteModel(name="SkillProposal"),
        migrations.DeleteModel(name="RoleSkillAssignment"),
    ]
