# Generated by Django 5.2.5 on 2026-06-08 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='paper-trading', max_length=64)),
                ('portfolio_id', models.CharField(default='default-paper', max_length=120)),
                ('account_id', models.CharField(default='local-paper', max_length=120)),
                ('strategy_id', models.CharField(default='default-strategy', max_length=120)),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Portfolio snapshot',
                'verbose_name_plural': 'Portfolio snapshots',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='KRW', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('portfolio_id', models.CharField(default='default-paper', max_length=120)),
                ('account_id', models.CharField(default='local-paper', max_length=120)),
                ('strategy_id', models.CharField(default='default-strategy', max_length=120)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_balances', to='portfolio.portfoliosnapshot')),
            ],
            options={
                'verbose_name': 'Cash balance',
                'verbose_name_plural': 'Cash balances',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('average_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('currency', models.CharField(default='KRW', max_length=16)),
                ('portfolio_id', models.CharField(default='default-paper', max_length=120)),
                ('account_id', models.CharField(default='local-paper', max_length=120)),
                ('strategy_id', models.CharField(default='default-strategy', max_length=120)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.portfoliosnapshot')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
    ]
