# Generated by Django 5.2.5 on 2026-06-14 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_brokerconnection_brokeraccount_instrumentmap'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='started', max_length=32)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pulled_positions_count', models.PositiveIntegerField(default=0)),
                ('pulled_cash_count', models.PositiveIntegerField(default=0)),
                ('pulled_orders_count', models.PositiveIntegerField(default=0)),
                ('pulled_fills_count', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('broker_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='integrations.brokerconnection')),
            ],
            options={
                'verbose_name': 'Broker sync run',
                'verbose_name_plural': 'Broker sync runs',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioLedgerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=32)),
                ('portfolio_id', models.CharField(default='default-paper', max_length=120)),
                ('account_id', models.CharField(default='local-paper', max_length=120)),
                ('strategy_id', models.CharField(default='default-strategy', max_length=120)),
                ('instrument_id', models.CharField(blank=True, max_length=120)),
                ('symbol', models.CharField(blank=True, max_length=64)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('currency', models.CharField(default='KRW', max_length=16)),
                ('event_at', models.DateTimeField(blank=True, null=True)),
                ('source_payload_hash', models.CharField(blank=True, max_length=64)),
                ('raw_payload_ref', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('broker_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_ledger_events', to='integrations.brokeraccount')),
                ('broker_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_ledger_events', to='integrations.brokerconnection')),
            ],
            options={
                'verbose_name': 'Portfolio ledger event',
                'verbose_name_plural': 'Portfolio ledger events',
                'ordering': ['-event_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_snapshot_ref', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='clean', max_length=32)),
                ('diffs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_runs', to='integrations.brokeraccount')),
                ('broker_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_runs', to='integrations.brokerconnection')),
                ('local_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_runs', to='portfolio.portfoliosnapshot')),
            ],
            options={
                'verbose_name': 'Reconciliation run',
                'verbose_name_plural': 'Reconciliation runs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
