# Generated by Django 5.2.5 on 2026-06-08 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvidencePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512, unique=True)),
                ('universe', models.CharField(default='public_equity', max_length=80)),
                ('workflow_type', models.CharField(blank=True, max_length=120)),
                ('source_posture', models.JSONField(blank=True, default=dict)),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evidence pack',
                'verbose_name_plural': 'Evidence packs',
            },
        ),
        migrations.CreateModel(
            name='ResearchArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_id', models.CharField(max_length=180, unique=True)),
                ('artifact_type', models.CharField(default='research_memo', max_length=80)),
                ('universe', models.CharField(default='public_equity', max_length=80)),
                ('workflow_type', models.CharField(blank=True, max_length=120)),
                ('symbol', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('markdown', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
                ('source_as_of', models.CharField(blank=True, max_length=120)),
                ('readiness_label', models.CharField(blank=True, max_length=80)),
                ('created_by', models.CharField(default='system', max_length=128)),
                ('content_hash', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('export_path', models.CharField(blank=True, max_length=512)),
                ('parent_artifact_id', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Research artifact',
                'verbose_name_plural': 'Research artifacts',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(max_length=120)),
                ('source_category', models.CharField(max_length=120)),
                ('as_of', models.CharField(blank=True, max_length=120)),
                ('artifact_id', models.CharField(blank=True, max_length=180)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Source snapshot',
                'verbose_name_plural': 'Source snapshots',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResearchArtifactVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('markdown', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workspace_context', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('created_by', models.CharField(default='system', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='research.researchartifact')),
            ],
            options={
                'verbose_name': 'Research artifact version',
                'verbose_name_plural': 'Research artifact versions',
                'ordering': ['-version', '-id'],
                'unique_together': {('artifact', 'version')},
            },
        ),
    ]
